language: python
python:
    - "3.5"
    - "3.8"
env:
    - DJANGO_SETTINGS_MODULE=workbench.settings
      MOZ_HEADLESS=1
install:
    - "pip install -r requirements/base.txt"
    - "pip install -r requirements/test.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt"
    - "pip install -e ."
    - "npm install"
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - tar xzf geckodriver-v0.26.0-linux64.tar.gz
    - sudo mv geckodriver /usr/local/bin/geckodriver
    - which geckodriver
script:
    - pep8 group_project_v2 tests --max-line-length=120 --ignore=E402
    - pylint group_project_v2 --rcfile=pylintrc
    - pylint tests --rcfile=tests/pylintrc
    - ./node_modules/jshint/bin/jshint group_project_v2 tests
    - ./node_modules/.bin/karma start tests/js/karma.conf.js --single-run
    - cat coverage/js/karma_coverage.txt
    - mkdir var
    - touch workbench.log
    - pytest
notifications:
  email: false
addons:
  firefox: "61.0.2"
cache:
  npm: true
  pip: true
